### ISSUE TITLE
Update deployment pypi packages process

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#289]
See https://github.com/pytrip/pytrip/issues/423

**Comment by grzanka** [comment]
The problem doesn't exists as we use:

```
# automatic deploy to github releases and pypi    
deploy:
  - provider: releases
  - provider: pypi
```

in .travis.yml.
